apiVersion: v1
name: codeartifact-chart
description: A Helm chart for the ACK service controller for CodeArtifact (codeArtifact)
version: 1.1.2
appVersion: 1.1.2
home: https://github.com/aws-controllers-k8s/codeartifact-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/codeartifact-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: codeArtifact Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/codeartifact-maintainer
keywords:
  - aws
  - kubernetes
  - codeartifact
